load_lib mike-gcc.exp

# This is done just to set the value of TORTURE_OPTIONS.
load_lib c-torture.exp

proc postbase_with_opts { src run groups } {
    global TORTURE_OPTIONS
    # loop through all the options
    foreach option $TORTURE_OPTIONS {
        postbase $src $run $groups $option
    }
}

prebase
set src_code 20021220.c
set compiler_output ".*:25:.*:30:.*:35:"
set groups {passed gcc-algor}
set actions compile
postbase $src_code $run $groups -O0
